name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake
        id: snake-gif
        uses: Platane/snk@v2
        with:
          github_user_name: Vinnixz

      - name: Show git status
        run: git status

      - name: Push changes
        uses: ad-m/github-push-action@v0.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: ${{ steps.snake-gif.outputs.gifPath }}  # Use a saída da ação snake-gif aqui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
